### ISSUE TITLE
Swift build error , on Linux devices

### ISSUE THREAD

**Issue by anmolhesta** [k-arindam/SwiftNP#13]
While building the project i get following error.

```
Building for debugging...
error: emit-module command failed with exit code 1 (use -v to see invocation)
/var/www/html/SwiftNP/Sources/SwiftNP/Core/NDArrayImpl/Conversions/MLMultiArray+NDArray.swift:9:8: error: no such module 'CoreML'
  7 | 
  8 | import Foundation
  9 | import CoreML
    |        `- error: no such module 'CoreML'
 10 | 

```

**Comment by k-arindam** [comment]
Importing `CoreML` in Swift is currently **not supported** on Linux environments. I’ll release a new build using `#if canImport(CoreML)` to import CoreML conditionally. This will ensure the Swift package can run and be tested on Linux targets without issues.

The `canImport()` directive checks if a specific module (in this case, `CoreML`) is available in the current build environment. If `CoreML` is available, the code inside the `#if canImport(CoreML)` block will be included; otherwise, it will be excluded. This way, platform-specific dependencies are handled **gracefully**.

**Comment by k-arindam** [comment]
@anmolhesta Kindly sync the latest changes, as they should resolve the issue.
